import discord
from database.db import get_pool
from cogs.dev.utils import check_access
from cogs.team.utils import get_app_by_channel, is_manage_or_admin, get_division_setting, get_division_by_code


async def team_accept(interaction: discord.Interaction):
    if not await check_access(interaction, "team"):
        return
    await interaction.response.defer()
    pool = await get_pool()
    gid = str(interaction.guild_id)

    app = await get_app_by_channel(str(interaction.channel_id), gid)
    if not app:
        await interaction.followup.send(embed=discord.Embed(
            description="❌ Use this command inside an application channel.",
            color=0xe74c3c
        ))
        return

    if not await is_manage_or_admin(interaction):
        await interaction.followup.send(embed=discord.Embed(
            description="❌ Requires MANAGE_APPLICATIONS or DIVISION_ADMIN.",
            color=0xe74c3c
        ))
        return

    if app['status'] == 'accepted':
        await interaction.followup.send(embed=discord.Embed(
            description="❌ This application is already accepted.",
            color=0xe74c3c
        ))
        return

    if app['status'] in ('rejected', 'withdrawn'):
        await interaction.followup.send(embed=discord.Embed(
            description=f"❌ This application is **{app['status']}** and cannot be accepted.",
            color=0xe74c3c
        ))
        return

    # Check team has at least one clan
    team = await pool.fetchrow(
        "SELECT * FROM teams WHERE guild_id=$1 AND division_code=$2 AND team_code=$3",
        gid, app['division_code'], app['team_code']
    )
    if not team or not team['main_clan']:
        await interaction.followup.send(embed=discord.Embed(
            description="❌ This team has no clan added. At least one clan is required before accepting.",
            color=0xe74c3c
        ))
        return

    await pool.execute("UPDATE applications SET status='accepted' WHERE id=$1", app['id'])
    await pool.execute(
        "UPDATE teams SET status='active' WHERE guild_id=$1 AND division_code=$2 AND team_code=$3",
        gid, app['division_code'], app['team_code']
    )

    # Add to division_participants
    div = await get_division_by_code(gid, app['division_code'])
    await pool.execute(
        """
        INSERT INTO division_participants (division_id, team_code, season, timezone)
        VALUES ($1, $2, $3, $4)
        ON CONFLICT (division_id, team_code, season) DO NOTHING
        """,
        div['id'], app['team_code'], div['season'], team['timezone']
    )

    # Rename channel
    try:
        new_name = f"✅-{app['team_name'].lower().replace(' ', '-')}"
        await interaction.channel.edit(name=new_name)
    except Exception:
        pass

    # Assign rep role if division has one
    if div['rep_role_id']:
        rep_role = interaction.guild.get_role(int(div['rep_role_id']))
        if rep_role:
            for rep_id in filter(None, [team['rep_id'], team['rep2_id']]):
                member = interaction.guild.get_member(int(rep_id))
                if member:
                    try:
                        await member.add_roles(rep_role)
                    except Exception:
                        pass

    # Welcome message
    welcome_msg = await get_division_setting(div['id'], 'welcome_message')

    # Ping rep
    await interaction.channel.send(f"<@{app['rep_id']}>")

    embed = discord.Embed(
        title="✅ Application Accepted",
        description=welcome_msg if welcome_msg else f"**{app['team_name']}** has been accepted into **{app['division_code']}**!\n\nWelcome to GBS. Good luck! 🏆",
        color=0x2ecc71
    )
    embed.add_field(name="Team", value=app['team_name'], inline=True)
    embed.add_field(name="Code", value=f"`{app['team_code']}`", inline=True)
    if team['logo_url']:
        embed.set_thumbnail(url=team['logo_url'])
    # GFX placeholder — will be generated by engine later
    await interaction.channel.send(embed=embed)

    await interaction.followup.send(embed=discord.Embed(
        description=f"✅ **{app['team_name']}** has been accepted.",
        color=0x2ecc71
    ))
